blog_post/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired
from flask import request


class SearchForm(FlaskForm):
    q = StringField(label='Search', validators=[DataRequired()], render_kw={"placeholder": "Search Posts"})

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)

blog_post/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectMultipleField
from wtforms.validators import DataRequired
from blog_post import CATEGORIES


class PostForm(FlaskForm):
    title = StringField(label="Title", validators=[DataRequired()])
    content = TextAreaField(label="Content", validators=[DataRequired()])
    category = SelectMultipleField(label="Category", choices=CATEGORIES)
    submit = SubmitField(label="Post")


class CommentForm(FlaskForm):
    comment = TextAreaField(validators=[DataRequired()], render_kw={"placeholder": "Share your thoughts"})
    submit = SubmitField(label="Submit")

blog_post/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from blog_post.config import Config
from flask_migrate import Migrate
from sqlalchemy import MetaData
from elasticsearch import Elasticsearch

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

db = SQLAlchemy(metadata=MetaData(naming_convention=naming_convention))
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = "info"
mail = Mail()
migrate = Migrate()

CATEGORIES = [('AI', 'Artificial Intelligence'), ('PY', 'Python'), ('DS', 'Data Science'), ('ML', 'Machine Learning'),
              ('Other', 'Other')]


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)
    from blog_post import models

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    migrate.init_app(app, db)

    app.elasticsearch = Elasticsearch([app.config['ELASTICSEARCH_URL']]) \
        if app.config['ELASTICSEARCH_URL'] else None

    from blog_post.users.routes import users
    from blog_post.posts.routes import posts
    from blog_post.main.routes import main
    from blog_post.errors.handlers import errors
    app.register_blueprint(users)
    app.register_blueprint(posts)
    app.register_blueprint(main)
    app.register_blueprint(errors)

    return app

blog_post/main/routes.py
from flask import render_template, request, Blueprint, current_app, flash, g, url_for, redirect
from flask_login import current_user, login_required
from blog_post.models import Post, Category, PostLikes
from blog_post.main.forms import SearchForm
from sqlalchemy import func

main = Blueprint('main', __name__)


@main.before_app_request
def before_request():
    g.search_form = SearchForm()


@main.route("/", defaults={'cat_name': None})
@main.route("/home", defaults={'cat_name': None}, methods=['GET', 'POST'])
@main.route("/home/<string:cat_name>/", methods=['GET', 'POST'])
def home(cat_name):
    page = request.args.get('page', 1, type=int)
    if cat_name and not current_user.is_authenticated:
        flash("Please Login to see more results.", "info")
    elif cat_name:
        posts = Post.query.filter(Post.categories.any(Category.name == cat_name)).order_by(Post.date_posted.desc()). \
            paginate(page=page, per_page=int(current_app.config["PER_PAGE"]))
        return render_template('home.html', title=cat_name, posts=posts, cat=cat_name)

    if not current_user.is_authenticated:
        posts = Post.query.join(PostLikes).group_by(Post.id).order_by(func.count().desc()). \
            paginate(page=1, per_page=int(current_app.config["PER_PAGE"]))
    else:
        posts = current_user.followed_posts().order_by(Post.date_posted.desc()). \
            paginate(page=page, per_page=int(current_app.config["PER_PAGE"]))

    return render_template('home.html', title="Home", posts=posts, route_name='home')


@main.route("/explore", methods=['GET', 'POST'])
@login_required
def explore():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()). \
        paginate(page=page, per_page=int(current_app.config["PER_PAGE"]))
    return render_template('home.html', title="Explore", posts=posts, route_name='explore')


@main.route("/search", methods=["GET", "POST"])
@login_required
def search():
    if not g.search_form.validate():
        return redirect(url_for('main.home'))
    page = request.args.get('page', 1, type=int)
    searched_posts, total = Post.search(g.search_form.q.data, page, int(current_app.config["PER_PAGE"]))
    if total == 0:
        return redirect(url_for('main.home'))
    if page == 1:
        flash("There are total {} results found...".format(total), "success")
    return render_template('home.html', title="Search",
                           posts=searched_posts.paginate(page=1, per_page=int(current_app.config["PER_PAGE"])),
                           route_name='search', q=g.search_form.q.data)


@main.route("/about")
def about():
    return render_template('about.html', title="About")

blog_post/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from blog_post import db
from blog_post.models import Post, Comment, PostLikes, Category
from blog_post.posts.forms import PostForm, CommentForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created!", "success")
        return redirect(url_for("main.home"))
    return render_template('create_update_post.html', title="New Post", form=form, legend="New Post")


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post_idx=post_id)
    likes = PostLikes.query.filter_by(liked_post_id=post_id).count()
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(comment_body=form.comment.data, commented_user=current_user, commented_post=post)
        db.session.add(comment)
        db.session.commit()
        flash("Your comment has been added", "success")
        return redirect(url_for("posts.post", post_id=post_id))
    return render_template("post.html", title=post.title, post=post, form=form, comments=comments, likes=likes)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    selected_cats = []
    for cat in post.categories:
        selected_cats.append(cat.name)
    form = PostForm(category=selected_cats)
    if form.validate_on_submit():
        for cat in form.category.data:
            category = Category.query.filter_by(name=cat).first()
            if post.categories.count(category) == 0:  # if post doesn't have that category associated already
                category.posts.append(post)
            else:  # remove the selected category of the post if it is already available.
                category.posts.remove(post)
            db.session.add(category)
            db.session.commit()
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Your post has been updated!", "success")
        return redirect(url_for("posts.post", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_update_post.html', title="Update Post", form=form, legend="Update Post")


@posts.route("/post/<int:post_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted!", "success")
    return redirect(url_for("main.home"))


@posts.route("/post/<int:post_id>/liked")
@login_required
def liked_post(post_id):
    post = Post.query.get_or_404(post_id)
    already_liked = PostLikes.query.filter_by(user=current_user, post=post).count() > 0
    if not already_liked:
        like = PostLikes(post=post, user=current_user)
        db.session.add(like)
        db.session.commit()
    return redirect(url_for("posts.post", post_id=post_id))

blog_post/users/routes.py
import os
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from flask_login import login_user, current_user, logout_user, login_required
from blog_post import db, bcrypt
from blog_post.models import User, Post, followers
from blog_post.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm, FollowForm)
from blog_post.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You can login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            if current_user.image_file and current_user.image_file !='default.jpg':
                old_img_path = os.path.join(current_app.root_path, 'static/profile_pics', current_user.image_file)
                if os.path.exists(old_img_path):
                    print(old_img_path)
                    os.remove(old_img_path)
                    print("File removed")
                else:
                    print("File Not Found")
                    print(old_img_path)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.profile', username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username  # initialize the fields with current data
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template("account.html", title="Account", image_file=image_file, form=form)


@users.route("/profile/<username>")
@login_required
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    n_following = user.followed.count()
    n_followers = user.followers.filter(followers.c.followed_id == user.id).count()
    n_posts = Post.query.filter_by(author=user).count()
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    form = FollowForm()
    return render_template('profile.html', image_file=image_file, user=user, form=form,
                           n_following=n_following, n_followers=n_followers, n_posts=n_posts)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=int(current_app.config["PER_PAGE"]))

    return render_template('user_posts.html', title="User Posts", posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/follow/<username>", methods=['POST'])
@login_required
def follow(username):
    form = FollowForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash("User {} is not found.".format(username))
            return redirect(url_for('main.home'))
        elif user == current_user:
            flash("You cannot follow yourself.")
            return redirect(url_for('users.profile', username=user.username))
        current_user.follow(user)
        db.session.commit()
        flash("You're now following {}.".format(username))
        return redirect(url_for('users.profile', username=user.username))
    else:
        return redirect(url_for('main.home'))


@users.route("/unfollow/<username>", methods=['POST'])
@login_required
def unfollow(username):
    form = FollowForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash("User {} is not found.".format(username))
            return redirect(url_for('main.home'))
        elif user == current_user:
            flash("You cannot unfollow yourself.")
            return redirect(url_for('users.profile', username=user.username))
        current_user.unfollow(user)
        db.session.commit()
        flash("You're no more following {}.".format(username))
        return redirect(url_for('users.profile', username=user.username))
    else:
        return redirect(url_for('main.home'))

blog_post/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
    <title>Flask Blog - {{ title }}</title>
    {% else %}
    <title>Flask Blog</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">Blog Post</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                    {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('main.explore') }}">Explore</a>
                    {% endif %}
                    <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
            </div>
            {% if current_user.is_authenticated %}
            <div class="collapse navbar-collapse">
                <div class="navbar-nav mr-auto">
            {% if g.search_form %}
            <form method="GET" action="{{ url_for('main.search') }}">
                {{ g.search_form.hidden_tag() }}
                <fieldset class="form-group" style="height:35px; margin-top:1.5%">
                    <div class="form-group" style="width:400px;">
                        {{ g.search_form.q(class="form-control form-control-sm") }}
                    </div>
                </fieldset>
            </form>
            {% endif %}
                </div>
            </div>
            {% endif %}
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.profile', username=current_user.username) }}">Profile</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
            </div>
        </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            {% block content %}{% endblock content %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>Trending Topics</h3>
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light"><a
                            href="{{ url_for('main.home', cat_name='AI') }}">Artificial Intelligence</a></li>
                    <li class="list-group-item list-group-item-light"><a
                            href="{{ url_for('main.home', cat_name='ML') }}">Machine Learning</a></li>
                    <li class="list-group-item list-group-item-light"><a
                            href="{{ url_for('main.home', cat_name='DS') }}">Data Science</a></li>
                    <li class="list-group-item list-group-item-light"><a
                            href="{{ url_for('main.home', cat_name='PY') }}">Python</a></li>
                </ul>
            </div>
        </div>
    </div>
</main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

blog_post/templates/login.html
{% extends "layout.html" %}
{% block content %}
	    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    
					{% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
				<small class="text-muted ml-2">
					<a href="{{url_for('users.reset_request')}}">Forgot Password?</a>
				</small>
			</div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

blog_post/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img"
         src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.profile', username=post.author.username) }}">{{ post.author.username
                }}</a>
            {% for cat in post.categories %}
            <span class="badge badge-secondary">{{cat.name}}</span>
            {% endfor %}
            <small class="text-muted" style="float:right">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            <div>
                {% if post.author == current_user %}
                <a class="btn btn-secondary btn-sm mt-1 mb-1"
                   href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
                    Delete
                </button>
                {% endif %}
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('posts.liked_post', post_id=post.id) }}" class="btn btn-info btn-sm mt-1 mb-1"
                   style="float:right">
                    <span class="glyphicon glyphicon-thumbs-up"></span> Like ({{ likes }}) </a>
                {% endif %}
            </div>
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>

<!--Comment Section-->
<section id="comments" class="body">
    <!--Comments-->
    <div class="card card-comments mb-3 wow fadeIn">
        <div class="card-header font-weight-bold">{{comments.count()}} Comments</div>
        <div class="card-body">
            {% for comment in comments %}
            <div class="media d-block d-md-flex mt-2">
                <img class="rounded-circle account-img"
                     src="{{ url_for('static', filename='profile_pics/' + comment.commented_user.image_file)}}">
                <div class="media-body text-center text-md-left ml-md-3 ml-0">
                    <h5 class="mt-0 font-weight-bold">{{comment.commented_user.username}}</h5>
                    <h6 style="float:right;">{{comment.comment_date.strftime('%d-%m-%Y')}}</h6>
                    {{comment.comment_body}}
                </div>
            </div>
            <hr>
            {% endfor %}
        </div>
    </div>
    <!--/.Comments-->

    {% if current_user.is_authenticated %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <div class="form-group">
                    {% if form.comment.errors %}
                    {{ form.comment(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.comment.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.comment(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    {% else %}
    <h6>Please log in to add your comment.</h6>
    <br>
    {% endif %}
</section>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content%}




blog_post/templates/profile.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
        {% if user == current_user %}
        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Edit Profile</a>
        {% elif not current_user.is_following(user) %}
        <p>
        <form action="{{ url_for('users.follow', username=user.username) }}" method="POST">
            {{ form.hidden_tag() }}
            {{ form.submit(value='Follow') }}
        </form>
        </p>
        {% else %}
        <p>
        <form action="{{ url_for('users.unfollow', username=user.username) }}" method="POST">
            {{ form.hidden_tag() }}
            {{ form.submit(value='Unfollow') }}
        </form>
        </p>
        {% endif %}
    </div>
</div>
<article class="media content-section">
    <div class="card-deck" style="width:100%;">
        <div class="card bg-success">
            <div class="card-body text-center">
                <h4 class="card-text" style="color:white">Posts: {{ n_posts }}</h4>
                <a href="{{url_for('users.user_posts', username=user.username)}}" class="btn btn-light btn-sm stretched-link">See Posts</a>
            </div>
        </div>
        <div class="card bg-primary">
            <div class="card-body text-center">
                <h4 class="card-text" style="color:white">Following: {{ n_following }}</h4>
            </div>
        </div>
        <div class="card bg-info">
            <div class="card-body text-center">
                <h4 class="card-text" style="color:white">Followers: {{ n_followers }}</h4>
            </div>
        </div>
        <!--<div class="card bg-info">-->
            <!--<div class="card-body text-center">-->
                <!--<h4 class="card-text">Some text inside the sixth card</h4>-->
            <!--</div>-->
        <!--</div>-->
    </div>
</article>
{% endblock content %}